sudo: false
language: android
jdk:
  - oraclejdk8
notifications:
  email: 
    on_success: never # default: change
    on_failure: always # default: always

# INSTRUMENTED TESTS ARE DISABLED - until Google or Travis fix the mess with emulation, only local tests are enabled
#  - sys-img-armeabi-v7a-android-24
install:
# Travis still uses 'android' command behind the 'components' section update.
# That command is obsolete and cannot update Android SDK Tools after 25.2.5.
# Let's solve it here with the new command 'sdkmanager'
- yes | sdkmanager --verbose "build-tools;26.0.2"
- yes | sdkmanager --verbose "platform-tools"
- yes | sdkmanager --verbose "tools"
- yes | sdkmanager --verbose "platforms;android-25"
- yes | sdkmanager --verbose "extras;android;m2repository"

# Check tools and dependencies installed
- yes | sdkmanager --list

#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - chmod +x ./wait_for_emulator.sh
#  - ./wait_for_emulator.sh
script:
# force init of adb way before any Gradle task that uses ADB; prevents a timeout error that skips emulators of android-24
  - adb devices
# build app and assemble APK, in debug mode
  - chmod +x gradlew
  - ./gradlew assemble
  - chmod +x deploy.sh
  - ./deploy.sh